#include "io_def.h"

// this file will be included twice when defining io data
// emit definitions only in phase 2 (or when IO_DEF_DEFINE is udefined)

#if IO_DEF_DEFINE != 1

DEF_IO(GPIOA, PIN0);
DEF_IO(GPIOA, PIN1);
DEF_IO(GPIOA, PIN2);
DEF_IO(GPIOA, PIN3);
DEF_IO(GPIOA, PIN4);
DEF_IO(GPIOA, PIN5);
DEF_IO(GPIOA, PIN6);
DEF_IO(GPIOA, PIN7);
DEF_IO(GPIOA, PIN8);
DEF_IO(GPIOA, PIN9);
DEF_IO(GPIOA, PIN10);
DEF_IO(GPIOA, PIN11);
DEF_IO(GPIOA, PIN12);
DEF_IO(GPIOA, PIN13);
DEF_IO(GPIOA, PIN14);
DEF_IO(GPIOA, PIN15);

DEF_IO(GPIOB, PIN0);
DEF_IO(GPIOB, PIN1);
DEF_IO(GPIOB, PIN2);
DEF_IO(GPIOB, PIN3);
DEF_IO(GPIOB, PIN4);
DEF_IO(GPIOB, PIN5);
DEF_IO(GPIOB, PIN6);
DEF_IO(GPIOB, PIN7);
DEF_IO(GPIOB, PIN8);
DEF_IO(GPIOB, PIN9);
DEF_IO(GPIOB, PIN10);
DEF_IO(GPIOB, PIN11);
DEF_IO(GPIOB, PIN12);
DEF_IO(GPIOB, PIN13);
DEF_IO(GPIOB, PIN14);
DEF_IO(GPIOB, PIN15);

DEF_IO(GPIOC, PIN13);
DEF_IO(GPIOC, PIN14);
DEF_IO(GPIOC, PIN15);

DEF_TIMER(TIM1, TIM1_CC_IRQn, TIM1_UP_IRQn, true);
DEF_TIMER(TIM2, TIM2_IRQn, TIM2_IRQn, false);
DEF_TIMER(TIM3, TIM3_IRQn, TIM3_IRQn, false);
DEF_TIMER(TIM4, TIM4_IRQn, TIM4_IRQn, false);
#if defined(STM32F10X_XL)
DEF_TIMER(TIM8, TIM8_CC_IRQn, TIM8_UP_TIM13_IRQn, true);
#elif defined( STM32F10X_HD)
DEF_TIMER(TIM8, TIM8_CC_IRQn, TIM8_UP_IRQn, true);
#endif

#endif
