#include "io_def.h"

// this file will be included twice when defining io data
// emit definitions only in phase 2 (or when IO_DEF_DEFINE is udefined)

#if IO_DEF_DEFINE != 1

DEF_IO(GPIOA, PIN0);
DEF_IO(GPIOA, PIN1);
DEF_IO(GPIOA, PIN2);
DEF_IO(GPIOA, PIN3);
DEF_IO(GPIOA, PIN4);
DEF_IO(GPIOA, PIN5);
DEF_IO(GPIOA, PIN6);
DEF_IO(GPIOA, PIN7);
DEF_IO(GPIOA, PIN8);
DEF_IO(GPIOA, PIN9);
DEF_IO(GPIOA, PIN10);
DEF_IO(GPIOA, PIN11);
DEF_IO(GPIOA, PIN12);
DEF_IO(GPIOA, PIN13);
DEF_IO(GPIOA, PIN14);
DEF_IO(GPIOA, PIN15);

DEF_IO(GPIOB, PIN0);
DEF_IO(GPIOB, PIN1);
DEF_IO(GPIOB, PIN2);
DEF_IO(GPIOB, PIN3);
DEF_IO(GPIOB, PIN4);
DEF_IO(GPIOB, PIN5);
DEF_IO(GPIOB, PIN6);
DEF_IO(GPIOB, PIN7);
DEF_IO(GPIOB, PIN8);
DEF_IO(GPIOB, PIN9);
DEF_IO(GPIOB, PIN10);
DEF_IO(GPIOB, PIN11);
DEF_IO(GPIOB, PIN12);
DEF_IO(GPIOB, PIN13);
DEF_IO(GPIOB, PIN14);
DEF_IO(GPIOB, PIN15);

DEF_IO(GPIOC, PIN13);
DEF_IO(GPIOC, PIN14);
DEF_IO(GPIOC, PIN15);

#endif
