
#pragma once

// can't use 0 
#define MAX_IRQ_PRIORITY    0
#define MAX_IRQ_SUBPRIORITY 1

#define TIMER_IRQ_PRIORITY 0
#define TIMER_IRQ_SUBPRIORITY 1

#define BARO_EXTIRQ_PRIORITY 0x0f
#define BARO_EXTIRQ_SUBPRIORITY 0x0f

#define WS2811_DMA_IRQ_PRIORITY 1             // TODO - is there some reason to use high priority? (or to use DMA a all?)
#define WS2811_DMA_IRQ_SUBPRIORITY 2

#define SERIALUART1_TXDMA_PRIORITY 1
#define SERIALUART1_TXDMA_SUBPRIORITY 0

#define SERIALUART1_IRQ_PRIORITY 1
#define SERIALUART1_IRQ_SUBPRIORITY 1

#define SERIALUART2_TXDMA_PRIORITY 1
#define SERIALUART2_TXDMA_SUBPRIORITY 0

#define SERIALUART2_IRQ_PRIORITY 1
#define SERIALUART2_IRQ_SUBPRIORITY 2

#define SERIALUART3_IRQ_PRIORITY 1
#define SERIALUART3_IRQ_SUBPRIORITY 2

#define I2C_ER_PRIORITY 1
#define I2C_ER_SUBPRIORITY 0
#define I2C_EV_PRIORITY 1
#define I2C_EV_SUBPRIORITY 0

#define CALLBACK_IRQ_PRIORITY 0x0f
#define CALLBACK_IRQ_SUBPRIORITY 0x0f
