#pragma once
// this file is automatically generated by def_generated.pl script
// do not modify this file, your changes will be lost

// make sure macros for all timers are defined
#ifndef TARGET_TIMER_TIM1
# define TARGET_TIMER_TIM1 -1
#endif
#ifndef TARGET_TIMER_TIM2
# define TARGET_TIMER_TIM2 -1
#endif
#ifndef TARGET_TIMER_TIM3
# define TARGET_TIMER_TIM3 -1
#endif
#ifndef TARGET_TIMER_TIM4
# define TARGET_TIMER_TIM4 -1
#endif
#ifndef TARGET_TIMER_TIM6
# define TARGET_TIMER_TIM6 -1
#endif
#ifndef TARGET_TIMER_TIM7
# define TARGET_TIMER_TIM7 -1
#endif
#ifndef TARGET_TIMER_TIM8
# define TARGET_TIMER_TIM8 -1
#endif
#ifndef TARGET_TIMER_TIM15
# define TARGET_TIMER_TIM15 -1
#endif
#ifndef TARGET_TIMER_TIM16
# define TARGET_TIMER_TIM16 -1
#endif
#ifndef TARGET_TIMER_TIM17
# define TARGET_TIMER_TIM17 -1
#endif

// generate mask with used timers
#if TARGET_TIMER_TIM1 > 0
# define TARGET_TIMER_TIM1_BIT BIT(1)
# define TARGET_TIMER_TIM1_INDEX  ( 0 )
#else
# define TARGET_TIMER_TIM1_BIT 0
# define TARGET_TIMER_TIM1_INDEX deftimer_error_TIMER1_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM2 > 0
# define TARGET_TIMER_TIM2_BIT BIT(2)
# define TARGET_TIMER_TIM2_INDEX  ( (TARGET_TIMER_TIM1 >= 0) )
#else
# define TARGET_TIMER_TIM2_BIT 0
# define TARGET_TIMER_TIM2_INDEX deftimer_error_TIMER2_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM3 > 0
# define TARGET_TIMER_TIM3_BIT BIT(3)
# define TARGET_TIMER_TIM3_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0) )
#else
# define TARGET_TIMER_TIM3_BIT 0
# define TARGET_TIMER_TIM3_INDEX deftimer_error_TIMER3_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM4 > 0
# define TARGET_TIMER_TIM4_BIT BIT(4)
# define TARGET_TIMER_TIM4_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0) )
#else
# define TARGET_TIMER_TIM4_BIT 0
# define TARGET_TIMER_TIM4_INDEX deftimer_error_TIMER4_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM6 > 0
# define TARGET_TIMER_TIM6_BIT BIT(6)
# define TARGET_TIMER_TIM6_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0)+(TARGET_TIMER_TIM4 >= 0) )
#else
# define TARGET_TIMER_TIM6_BIT 0
# define TARGET_TIMER_TIM6_INDEX deftimer_error_TIMER6_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM7 > 0
# define TARGET_TIMER_TIM7_BIT BIT(7)
# define TARGET_TIMER_TIM7_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0)+(TARGET_TIMER_TIM4 >= 0)+(TARGET_TIMER_TIM6 >= 0) )
#else
# define TARGET_TIMER_TIM7_BIT 0
# define TARGET_TIMER_TIM7_INDEX deftimer_error_TIMER7_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM8 > 0
# define TARGET_TIMER_TIM8_BIT BIT(8)
# define TARGET_TIMER_TIM8_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0)+(TARGET_TIMER_TIM4 >= 0)+(TARGET_TIMER_TIM6 >= 0)+(TARGET_TIMER_TIM7 >= 0) )
#else
# define TARGET_TIMER_TIM8_BIT 0
# define TARGET_TIMER_TIM8_INDEX deftimer_error_TIMER8_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM15 > 0
# define TARGET_TIMER_TIM15_BIT BIT(15)
# define TARGET_TIMER_TIM15_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0)+(TARGET_TIMER_TIM4 >= 0)+(TARGET_TIMER_TIM6 >= 0)+(TARGET_TIMER_TIM7 >= 0)+(TARGET_TIMER_TIM8 >= 0) )
#else
# define TARGET_TIMER_TIM15_BIT 0
# define TARGET_TIMER_TIM15_INDEX deftimer_error_TIMER15_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM16 > 0
# define TARGET_TIMER_TIM16_BIT BIT(16)
# define TARGET_TIMER_TIM16_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0)+(TARGET_TIMER_TIM4 >= 0)+(TARGET_TIMER_TIM6 >= 0)+(TARGET_TIMER_TIM7 >= 0)+(TARGET_TIMER_TIM8 >= 0)+(TARGET_TIMER_TIM15 >= 0) )
#else
# define TARGET_TIMER_TIM16_BIT 0
# define TARGET_TIMER_TIM16_INDEX deftimer_error_TIMER16_is_not_enabled_on_target
#endif
#if TARGET_TIMER_TIM17 > 0
# define TARGET_TIMER_TIM17_BIT BIT(17)
# define TARGET_TIMER_TIM17_INDEX  ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0)+(TARGET_TIMER_TIM4 >= 0)+(TARGET_TIMER_TIM6 >= 0)+(TARGET_TIMER_TIM7 >= 0)+(TARGET_TIMER_TIM8 >= 0)+(TARGET_TIMER_TIM15 >= 0)+(TARGET_TIMER_TIM16 >= 0) )
#else
# define TARGET_TIMER_TIM17_BIT 0
# define TARGET_TIMER_TIM17_INDEX deftimer_error_TIMER17_is_not_enabled_on_target
#endif
#define TIMER_USED_BITS  ( TARGET_TIMER_TIM1_BIT|TARGET_TIMER_TIM2_BIT|TARGET_TIMER_TIM3_BIT|TARGET_TIMER_TIM4_BIT|TARGET_TIMER_TIM6_BIT|TARGET_TIMER_TIM7_BIT|TARGET_TIMER_TIM8_BIT|TARGET_TIMER_TIM15_BIT|TARGET_TIMER_TIM16_BIT|TARGET_TIMER_TIM17_BIT )
#define TIMER_USED_COUNT ( (TARGET_TIMER_TIM1 >= 0)+(TARGET_TIMER_TIM2 >= 0)+(TARGET_TIMER_TIM3 >= 0)+(TARGET_TIMER_TIM4 >= 0)+(TARGET_TIMER_TIM6 >= 0)+(TARGET_TIMER_TIM7 >= 0)+(TARGET_TIMER_TIM8 >= 0)+(TARGET_TIMER_TIM15 >= 0)+(TARGET_TIMER_TIM16 >= 0)+(TARGET_TIMER_TIM17 >= 0) )

// structure to hold all timerRec_t.
// Number of channels per timer is user specifed, structure will ensure correct packing
struct timerRec_all {
#if TARGET_TIMER_TIM1 >= 0
    timerRec_t rec_TIM1;
# if TARGET_TIMER_TIM1 > 0
    timerChRec_t rec_TIM1_ch[TARGET_TIMER_TIM1];
# endif
#endif
#if TARGET_TIMER_TIM2 >= 0
    timerRec_t rec_TIM2;
# if TARGET_TIMER_TIM2 > 0
    timerChRec_t rec_TIM2_ch[TARGET_TIMER_TIM2];
# endif
#endif
#if TARGET_TIMER_TIM3 >= 0
    timerRec_t rec_TIM3;
# if TARGET_TIMER_TIM3 > 0
    timerChRec_t rec_TIM3_ch[TARGET_TIMER_TIM3];
# endif
#endif
#if TARGET_TIMER_TIM4 >= 0
    timerRec_t rec_TIM4;
# if TARGET_TIMER_TIM4 > 0
    timerChRec_t rec_TIM4_ch[TARGET_TIMER_TIM4];
# endif
#endif
#if TARGET_TIMER_TIM6 >= 0
    timerRec_t rec_TIM6;
# if TARGET_TIMER_TIM6 > 0
    timerChRec_t rec_TIM6_ch[TARGET_TIMER_TIM6];
# endif
#endif
#if TARGET_TIMER_TIM7 >= 0
    timerRec_t rec_TIM7;
# if TARGET_TIMER_TIM7 > 0
    timerChRec_t rec_TIM7_ch[TARGET_TIMER_TIM7];
# endif
#endif
#if TARGET_TIMER_TIM8 >= 0
    timerRec_t rec_TIM8;
# if TARGET_TIMER_TIM8 > 0
    timerChRec_t rec_TIM8_ch[TARGET_TIMER_TIM8];
# endif
#endif
#if TARGET_TIMER_TIM15 >= 0
    timerRec_t rec_TIM15;
# if TARGET_TIMER_TIM15 > 0
    timerChRec_t rec_TIM15_ch[TARGET_TIMER_TIM15];
# endif
#endif
#if TARGET_TIMER_TIM16 >= 0
    timerRec_t rec_TIM16;
# if TARGET_TIMER_TIM16 > 0
    timerChRec_t rec_TIM16_ch[TARGET_TIMER_TIM16];
# endif
#endif
#if TARGET_TIMER_TIM17 >= 0
    timerRec_t rec_TIM17;
# if TARGET_TIMER_TIM17 > 0
    timerChRec_t rec_TIM17_ch[TARGET_TIMER_TIM17];
# endif
#endif
};
